version: "3"

services:
  backend:
    image: custom-school-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379

  frontend:
    image: custom-school-app:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      - BACKEND=backend:8000
      - FRAPPE_SITE_NAME_HEADER=$$host
      - SOCKETIO=websocket:9000
      - UPSTREAM_REAL_IP_ADDRESS=127.0.0.1
      - UPSTREAM_REAL_IP_HEADER=X-Forwarded-For
      - UPSTREAM_REAL_IP_RECURSIVE=off
      - PROXY_READ_TIMEOUT=120
      - CLIENT_MAX_BODY_SIZE=50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "80:8080"

  db:
    image: mariadb:10.6
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MARIADB_USER=frappe
      - MARIADB_PASSWORD=frappe
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    deploy:
      restart_policy:
        condition: on-failure

  redis-queue:
    image: redis:alpine
    deploy:
      restart_policy:
        condition: on-failure

  redis-socketio:
    image: redis:alpine
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  sites:
  logs:
  db-data:
